### ISSUE TITLE
Initialize board from a FEN string

### ISSUE THREAD

**Issue by roh1th-s** [acmpesuecc/chess-opengl#3]
Implement a function to initialize  the chess board from a [FEN String](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation). This would make testing much easier since we can start games from specific positions.

- Write your code in [board.c](https://github.com/acmpesuecc/chess-opengl/blob/48e3c7419767d6e82a6403c2db3b28dce9c53257/src/chess/board.c).  Suggested function signature: `chess_board_from_fen(ChessBoard *self, const char *fen)`
- Make sure to handle all parts of the FEN string correctly, including current turn, castling rights and en passant status.

**Comment by Dhan1211** [comment]
Can I get this assigned?

**Comment by Dhan1211** [comment]
I am going for dinner. Please extend the time

**Comment by roh1th-s** [comment]
!extend 60

**Comment by roh1th-s** [comment]
!assign @Dhan1211 60

**Comment by roh1th-s** [comment]
!assign @Dhan1211 60

**Comment by CodeWithBhuvan** [comment]
Can you assign me this issue?

**Comment by Rojas-Binny** [comment]
Can I get assigned to this?

**Comment by roh1th-s** [comment]
!assign @Rojas-Binny

**Comment by Redslayer112** [comment]
please assign me @Redslayer112 -> github username

**Comment by Omkar-Patil-08-05** [comment]
please assign me

**Comment by roh1th-s** [comment]
!deassign

**Comment by roh1th-s** [comment]
@Omkar-Patil-08-05 you may work on this

**Comment by CodeWithBhuvan** [comment]
Can you assign me this issue?

**Comment by roh1th-s** [comment]
!assign @CodeWithBhuvan

**Comment by roh1th-s** [comment]
!extend 30
